# Generated by Django 5.2.8 on 2025-11-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='descricao',
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Instrutor'), (2, 'Usuário')], default=2, unique=True),
        ),
    ]
