# Generated by Django 5.2.8 on 2025-11-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_remove_perfil_descricao_perfil_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Instrutor'), (2, 'Usuário')], unique=True),
        ),
    ]
