# Generated by Django 5.2.8 on 2025-11-16 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_alter_perfil_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='academia.perfil'),
        ),
    ]
