# Generated by Django 5.2.8 on 2025-11-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissao',
            options={'permissions': [('acessar_area_restrita', 'Pode acessar a área restrita')]},
        ),
        migrations.AlterField(
            model_name='permissao',
            name='descricao',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
