# Generated by Django 5.2.8 on 2025-11-17 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_alter_permissao_options_alter_permissao_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
    ]
