# Generated by Django 5.2.8 on 2025-11-17 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_remove_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treino',
            name='carga',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='exercicio',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='repeticao',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='series',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='usuario',
        ),
        migrations.AddField(
            model_name='treino',
            name='nivel_experiencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treino',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='treino',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='objetivo',
            field=models.CharField(choices=[('emagrecimento', 'Emagrecimento'), ('resistencia', 'Resistência'), ('reabilitacao', 'Reabilitação'), ('hipertrofia', 'Hipertrofia')], max_length=50),
        ),
        migrations.CreateModel(
            name='PlanoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(choices=[('emagrecimento', 'Emagrecimento'), ('resistencia', 'Resistência'), ('reabilitacao', 'Reabilitação'), ('hipertrofia', 'Hipertrofia')], max_length=50)),
                ('frequencia_semanal', models.PositiveIntegerField(default=3)),
                ('duracao_semanas', models.PositiveIntegerField(default=8)),
                ('aprovado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_criados', to=settings.AUTH_USER_MODEL)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.treino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreinoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('series', models.CharField(blank=True, max_length=50)),
                ('repeticoes', models.CharField(blank=True, max_length=50)),
                ('intensidade', models.CharField(blank=True, max_length=50)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.treino')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='treino',
            name='exercicios',
            field=models.ManyToManyField(through='academia.TreinoExercicio', to='academia.exercicio'),
        ),
    ]
