# Generated by Django 5.2.8 on 2025-11-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_remove_treino_carga_remove_treino_exercicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('emagrecimento', 'Emagrecimento'), ('resistencia', 'Resistência'), ('reabilitacao', 'Reabilitação'), ('musculacao', 'Musculação')], max_length=50, null=True),
        ),
    ]
